exclude: [makebom.py]
pygments: true

navigation:
- text: Home
  url: /
- text: API Docs
  url: /Open-Notify-API
  name: apidoc
- text: Source Code
  url: https://github.com/open-notify
- text: About
  url: /about.html

hardlinks:
 - text: ISS Notify Hardware Docs
   url: /ISS-Notify-Hardware
   name: harddocs
 - text: Bill of Materials
   url: /ISS-Notify-Hardware/BOM
   name: BOM
